/**
 * Compact Map interface - matches the type generated by Compact compiler.
 * Used in tests to avoid depending on the auto-generated managed/ types directly.
 */
export type CompactMap<K, V> = {
  isEmpty(): boolean;
  size(): bigint;
  member(key_0: K): boolean;
  lookup(key_0: K): V;
  [Symbol.iterator](): Iterator<[K, V]>;
};

/**
 * Shape of the Age Gate ledger state.
 * Must match what `ledger()` returns from the managed contract.
 */
export type AgeLedger = {
  readonly eligible: CompactMap<Uint8Array, boolean>;
  readonly verification_timestamp: CompactMap<Uint8Array, bigint>;
};
